services:
  postgres-db:
    image: postgres:13
    environment:
      POSTGRES_DB: production
      POSTGRES_USER: ahona
      POSTGRES_PASSWORD: ahona
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: ahona
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres-db

volumes:
  pg_data:
  pgadmin_data:
